# Generated by Django 5.2.1 on 2025-05-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GBMTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("dividend", "Dividend"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("price_usd", models.FloatField(blank=True, null=True)),
                ("amount_usd", models.FloatField(blank=True, null=True)),
                ("tax_withheld_usd", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
