# Generated by Django 5.2.1 on 2025-05-29 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_gbmconfirmationtransaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GBMTransaction",
        ),
        migrations.AddField(
            model_name="gbmconfirmationtransaction",
            name="execution_time",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="gbmconfirmationtransaction",
            name="upload_date",
            field=models.DateField(
                auto_now_add=True, default=datetime.date(2025, 1, 1)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gbmconfirmationtransaction",
            name="capacity",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="gbmconfirmationtransaction",
            name="commission",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gbmconfirmationtransaction",
            name="other_fees",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gbmconfirmationtransaction",
            name="security_name",
            field=models.CharField(default="UNKNOWN", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gbmconfirmationtransaction",
            name="transaction_fee",
            field=models.FloatField(),
        ),
    ]
