# Generated by Django 5.2.1 on 2025-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_delete_gbmtransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gbmconfirmationtransaction",
            name="mxn_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
