# Generated by Django 5.2.1 on 2025-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_gbmconfirmationtransaction_capital_gain_mxn"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("rate", models.FloatField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
